---
- name: Enable Remote Desktop Service
  hosts: all  # Replace with your target host or group name
  gather_facts: yes      # Disable gathering facts to speed up the playbook

  tasks:
    - name: Enable Remote Desktop
      win_shell: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      become: no
    
    - name: Enable ssh server 
      win_command: |
        powershell
        Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH*'
        add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
        add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
        Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH*'
        Start-Service sshd
        Set-Service -Name sshd -StartupType 'Automatic'
      ignore_errors: true
      tags:
        ssh





      
