---
- name: Install and Promote Domain Controller
  hosts: "*"
  gather_facts: false

  tasks:
    - name: Copy promote script to windox 
      ansible.windows.win_copy:
        src:  /config/workspace/Windows/Promote/install.ps1
        dest: C:\Users\Administrator\Desktop\install.ps1
    
    - name: Install and Promote Domain Controller
      ansible.windows.win_shell: 
        powershell -file C:\Users\Administrator\Desktop/install.ps1
    
